from __future__ import annotations

import argparse
import json
import re
from collections import Counter, defaultdict
from pathlib import Path

from script_common import fail, get_repo_root, run_cli


DEFAULT_INPUT = Path("defaults") / "catalog" / "RandomLoadout.pickups.by-category.json"
DEFAULT_OUTPUT = Path("docs") / "reference" / "pickups.md"
DEFAULT_ALIAS_INPUT = Path("defaults") / "config" / "RandomLoadout.aliases.json5"
CATEGORY_ORDER = ("Gun", "Passive", "Active")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a user-facing pickup reference from the grouped pickup catalog snapshot."
    )
    parser.add_argument(
        "-i",
        "--input",
        default=str(DEFAULT_INPUT),
        help="Path to the grouped pickup catalog JSON. Defaults to defaults/catalog/RandomLoadout.pickups.by-category.json.",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=str(DEFAULT_OUTPUT),
        help="Path to write the generated Markdown document. Defaults to docs/reference/pickups.md.",
    )
    parser.add_argument(
        "--alias-input",
        default=str(DEFAULT_ALIAS_INPUT),
        help="Optional alias JSON5 file used to annotate known aliases. Defaults to defaults/config/RandomLoadout.aliases.json5.",
    )
    return parser.parse_args()


def load_json_file(path: Path) -> object:
    with path.open("r", encoding="utf-8") as file_obj:
        return json.load(file_obj)


def load_json5_file(path: Path) -> object:
    raw_text = path.read_text(encoding="utf-8")
    sanitized = re.sub(r"/\*[\s\S]*?\*/", "", raw_text)
    sanitized = re.sub(r"//.*", "", sanitized)
    sanitized = re.sub(r",(\s*[}\]])", r"\1", sanitized)
    return json.loads(sanitized)


def normalize_name(value: str) -> str:
    return value.strip().lower()


def build_alias_lookup(alias_data: object) -> dict[int, list[str]]:
    aliases_by_id: dict[int, list[str]] = defaultdict(list)
    if not isinstance(alias_data, dict):
        return aliases_by_id

    entries = alias_data.get("aliases", [])
    if not isinstance(entries, list):
        return aliases_by_id

    for entry in entries:
        if not isinstance(entry, dict):
            continue

        alias = str(entry.get("alias", "")).strip()
        pickup_id = entry.get("id")
        if not alias or not isinstance(pickup_id, int):
            continue

        aliases_by_id[pickup_id].append(alias)

    return aliases_by_id


def format_aliases(aliases: list[str]) -> str:
    if not aliases:
        return "-"

    return ", ".join("`{0}`".format(alias) for alias in aliases)


def format_notes(display_name: str, duplicate_count: int) -> str:
    if duplicate_count > 1:
        return "Display name is ambiguous ({0} matches). Prefer `id`, `alias`, or `internalName`.".format(duplicate_count)

    return "Internal name or ID is recommended. Display name input should also work."


def format_table_row(item: dict[str, object], aliases: list[str], duplicate_count: int) -> str:
    display_name = str(item.get("displayName", "")).strip()
    pickup_id = int(item.get("pickupId", 0))
    quality = str(item.get("quality", "")).strip() or "-"
    internal_name = str(item.get("internalName", "")).strip() or "-"
    notes = format_notes(display_name, duplicate_count)

    return "| {0} | `{1}` | {2} | `{3}` | `{4}` | {5} |".format(
        escape_pipes(display_name or "-"),
        pickup_id,
        format_aliases(aliases),
        quality,
        escape_pipes(internal_name),
        escape_pipes(notes),
    )


def escape_pipes(value: str) -> str:
    return value.replace("|", "\\|")


def generate_markdown(catalog_data: object, aliases_by_id: dict[int, list[str]]) -> str:
    if not isinstance(catalog_data, dict):
        raise ValueError("Catalog root must be a JSON object.")

    categories = catalog_data.get("categories")
    if not isinstance(categories, dict):
        raise ValueError("Catalog JSON must contain a 'categories' object.")

    generated_utc = str(catalog_data.get("generatedUtc", "")).strip() or "unknown"
    entry_count = int(catalog_data.get("entryCount", 0))

    all_display_names: list[str] = []
    for category_items in categories.values():
        if not isinstance(category_items, list):
            continue

        for item in category_items:
            if not isinstance(item, dict):
                continue

            display_name = str(item.get("displayName", "")).strip()
            if display_name:
                all_display_names.append(display_name)

    duplicate_counts = Counter(normalize_name(name) for name in all_display_names)

    lines: list[str] = []
    lines.append("# Pickups")
    lines.append("")
    lines.append("This file is generated by `python .\\scripts\\generate_pickup_docs.py`.")
    lines.append("Do not hand-edit it; regenerate it from the grouped pickup catalog snapshot when the source data changes.")
    lines.append("")
    lines.append("## How To Use")
    lines.append("")
    lines.append("- Prefer `pickupId` when exact matching matters or when you are copying values from config/catlog files.")
    lines.append("- Prefer `internalName` for string input. This matches the project command behavior more closely to `ModTheGungeonAPI give`.")
    lines.append("- Use `alias` when one is listed.")
    lines.append("- `Display Name` is still accepted as a compatibility fallback, but it can be less stable because it depends on runtime-localized strings.")
    lines.append("- Command examples:")
    lines.append("  - `gun Casey`")
    lines.append("  - `gun 541`")
    lines.append("  - `gun casey_bat`")
    lines.append("  - `passive PlatinumBullets`")
    lines.append("")
    lines.append("## Snapshot")
    lines.append("")
    lines.append("- Source: `defaults/catalog/RandomLoadout.pickups.by-category.json`")
    lines.append("- Generated UTC: `{0}`".format(generated_utc))
    lines.append("- Entry count: `{0}`".format(entry_count))
    lines.append("")

    for category_name in CATEGORY_ORDER:
        raw_items = categories.get(category_name, [])
        if not isinstance(raw_items, list):
            continue

        items = [item for item in raw_items if isinstance(item, dict)]
        items.sort(key=lambda item: (str(item.get("displayName", "")).lower(), int(item.get("pickupId", 0))))

        lines.append("## {0}".format(category_name))
        lines.append("")
        lines.append("Count: `{0}`".format(len(items)))
        lines.append("")
        lines.append("| Display Name | ID | Alias | Quality | Internal Name | Notes |")
        lines.append("| --- | --- | --- | --- | --- | --- |")

        for item in items:
            pickup_id = int(item.get("pickupId", 0))
            display_name = str(item.get("displayName", "")).strip()
            duplicate_count = duplicate_counts.get(normalize_name(display_name), 0)
            item_aliases = aliases_by_id.get(pickup_id, [])
            lines.append(format_table_row(item, item_aliases, duplicate_count))

        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    repo_root = get_repo_root()

    input_path = (repo_root / Path(args.input)).resolve()
    output_path = (repo_root / Path(args.output)).resolve()
    alias_input_path = (repo_root / Path(args.alias_input)).resolve()

    if not input_path.is_file():
        return fail("Grouped pickup catalog not found: {0}".format(input_path))

    try:
        catalog_data = load_json_file(input_path)
    except json.JSONDecodeError as error:
        return fail("Invalid JSON in grouped pickup catalog '{0}': {1}".format(input_path, error))

    alias_data: object = {}
    if alias_input_path.is_file():
        try:
            alias_data = load_json5_file(alias_input_path)
        except json.JSONDecodeError as error:
            return fail("Invalid JSON5 in alias file '{0}': {1}".format(alias_input_path, error))

    markdown = generate_markdown(catalog_data, build_alias_lookup(alias_data))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(markdown, encoding="utf-8")
    print("Generated pickup reference: {0}".format(output_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(run_cli(main))
